DROP TABLE BACKUP;
DROP TABLE LOG;

DROP TABLE ROOM;
DROP TABLE PATHFINDER;

DROP TABLE REQUEST;
DROP TABLE MESSAGE;

DROP TABLE STAFF;
DROP TABLE USERPASSWORD;
DROP TABLE USERACCOUNT;

DROP TABLE MAP_EDGES;
DROP TABLE MAP_NODES;